#!/bin/bash

url=$1
github_url="https://github.com/andrewboy/termux-yt-dl/raw/main"
download_path="$HOME/storage/downloads/youtube-dl"
# download_path="$PWD/downloads"
output_path="$download_path/%(title)s.%(ext)s"
chapters_output_path="chapter:$download_path/%(title)s/[%(section_number)s] - %(section_title)s.%(ext)s"

video_menu() {
  clear

  menu_result=$(dialog \
  --clear \
  --stdout \
  --backtitle "Video Downloader" \
  --title "Video Downloader" \
  --menu "Choose:" \
  11 40 4 \
  1 "download video" \
  2 "download audio" \
  3 "download subtitle" \
  4 "update");

  local menuExitCode=$?

  clear

  [ "$menuExitCode" == 1 ] && exit 0

  #create directory if not exists
  [ ! -d "$download_path" ] && mkdir -p "$download_path"

  if [ "$menu_result" == 1 ]; then
    checklist_result=$(dialog \
      --checklist \
      --stdout \
      "Select choices" 8 40 2 \
      a "Split chapters" off);

    local checklistExitCode=$?

    clear

    if [ "$checklistExitCode" == 1 ]; then
      video_menu

      return 1 # or return 0, or even you can omit the argument.
    fi

    local video_params=" -c -i"

    video_params+=" $url"

    if [[ $checklist_result =~ "a" ]]; then
      video_params+=" --split-chapters"

      yt-dlp $video_params -o "$chapters_output_path" --exec rm
    else
      yt-dlp $video_params -o "$output_path"
    fi

    # clear
    # dialog \
    #   --yesno "Do you want to download the subtitle too(English)?" \
    #   0 0
    # if [ "$?" == 0 ]; then
    #   withSubs="--write-sub --write-auto-sub"
    #   #--sub-lang \"en.*\"
    # else
    #   withSubs=""
    # fi
    # clear
    # yt-dlp ${withSubs} -c -i "$url" -o "$download_path/$file_name"
  elif [ "$menu_result" == 2 ]; then
    yt-dlp \
      -x \
      --audio-format "mp3" \
      -c \
      -i "$url" \
      -o "$output_path"
  elif [ "$menu_result" == 3 ]; then
    yt-dlp \
      --skip-download \
      --write-sub \
      --write-auto-sub \
      -c \
      -i "$url" \
      -o "$output_path"
  elif [ "$menu_result" == 4 ]; then
    curl -sSL "$github_url/install.sh" | bash
    video_menu
  else
    echo "Unrecognized choice"
  fi
}

video_menu